/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// int printf(const char *format, ...);
// int puts(const char *s);
// int __gmon_start__(void); weak
// void exit(int status);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int __isoc99_scanf(const char *, ...); weak
void _x86_get_pc_thunk_bx();
signed int deregister_tm_clones();
int register_tm_clones();
signed int _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
int _libc_csu_init();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
char *str = "Got %s\n"; // idb
FILE *stdout; // idb
char completed_6591; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0804837C) --------------------------------------------------------
int init_proc()
{
  int result; // eax@1

  result = (int)&_gmon_start__;
  if ( &_gmon_start__ )
    result = __gmon_start__();
  return result;
}
// 80483D0: using guessed type int __gmon_start__(void);

//----- (08048420) --------------------------------------------------------
#error "8048423: positive sp value has been found (funcsize=2)"

//----- (08048450) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (08048460) --------------------------------------------------------
signed int deregister_tm_clones()
{
  return 3;
}
// 8048460: could not find valid save-restore pair for ebp

//----- (08048490) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 8048490: could not find valid save-restore pair for ebp

//----- (080484D0) --------------------------------------------------------
signed int _do_global_dtors_aux()
{
  signed int result; // eax@2

  if ( !completed_6591 )
  {
    result = deregister_tm_clones();
    completed_6591 = 1;
  }
  return result;
}
// 80484D0: could not find valid save-restore pair for ebp
// 804A044: using guessed type char completed_6591;

//----- (080484F0) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 80484F0: could not find valid save-restore pair for ebp

//----- (0804851D) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v4; // [sp+18h] [bp-88h]@1
  double v5; // [sp+98h] [bp-8h]@1

  v5 = 64.33333;
  setvbuf(stdout, 0, 2, 0);
  printf("Buff: %p\n", &v4);
  __isoc99_scanf("%s", &v4);
  if ( 64.33333 != v5 )
  {
    puts("Nope");
    exit(1);
  }
  return printf(str, &v4);
}
// 8048410: using guessed type int __isoc99_scanf(const char *, ...);

//----- (080485E0) --------------------------------------------------------
int _libc_csu_init()
{
  int v0; // edi@1
  int result; // eax@1
  signed int v2; // esi@1

  v0 = 0;
  init_proc();
  result = (int)_frame_dummy_init_array_entry;
  v2 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  if ( v2 )
  {
    do
      result = _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v2 );
  }
  return result;
}
// 8049F08: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 8049F0C: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();

//----- (08048654) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 10 function(s)"
